name: Binary Rambles
description: Blogging about all things tech.
meta_description: "Binary Rambles: Blogging about all things tech."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jordanjtw.github.io'

url: 'jordanjtw.github.io'
author:
  name: 'Jordan Werthman'
  android: 'BinaryOne+Apps'
  github: 'JordanJTW'
  gmail: 'jordanwerthman@gmail.com'
  linkedin: '266312995'